"""Add SEO settings

Revision ID: 14a424ae8f1a
Revises: e534842a308d
Create Date: 2024-11-17 10:00:06.858306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a424ae8f1a'
down_revision = 'e534842a308d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('og_image', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('og_image_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('og_image_type')
        batch_op.drop_column('og_image')

    # ### end Alembic commands ###
