"""empty message

Revision ID: 6fb958d3c87e
Revises: 5d2335c225f1
Create Date: 2024-11-14 08:44:37.615649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb958d3c87e'
down_revision = '5d2335c225f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('featured_image_mimetype', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('featured_image_mimetype')
        batch_op.drop_column('featured_image_data')

    # ### end Alembic commands ###
